#!/bin/bash
function line {
echo -e "$YELLOW  ----------------------------------------------------------------------------------- $NORMAL"
}
function colors {
  YELLOW="\e[1;33m"
  NORMAL="\e[0m"
}
colors
line
echo -e "$YELLOW |                    0000000            0000000       00000000000                   |$NORMAL"
echo -e "$YELLOW |                 000       000      000       000    00000000000                   |$NORMAL"
echo -e "$YELLOW |                00           00    00           00   00                            |$NORMAL"
echo -e "$YELLOW |               00             00  00             00  00000000000                   |$NORMAL"
echo -e "$YELLOW |               00             00  00             00  00000000000                   |$NORMAL"
echo -e "$YELLOW |               00             00  00             00  00                            |$NORMAL"
echo -e "$YELLOW |               00             00  00             00  00                            |$NORMAL"
echo -e "$YELLOW |                00           00    00           00   00                            |$NORMAL"
echo -e "$YELLOW |                 000       000      000       000    00                            |$NORMAL"
echo -e "$YELLOW |                    0000000            0000000       00                            |$NORMAL"
echo -e "$YELLOW |                                                                                   |$NORMAL"
echo -e "$YELLOW |000           000      0000000        0000000        0000000000000      000000000  |$NORMAL"
echo -e "$YELLOW |00000         000   000       000     000  0000      0000000000000.   00000        |$NORMAL"
echo -e "$YELLOW |000 0000      000  00           00    000    0000    000.                000       |$NORMAL"
echo -e "$YELLOW |000   000     000 00             00   000       000  000.                  000     |$NORMAL"
echo -e "$YELLOW |000    000    000 00             00   000       000  0000000000000.          000   |$NORMAL"
echo -e "$YELLOW |000     000   000 00             00   000       000. 0000000000000.            000 |$NORMAL"
echo -e "$YELLOW |000      000  000 00             00   000       000  000                        000| $NORMAL"
echo -e "$YELLOW |000       000 000  00           00    000    0000    000.                    0000  |$NORMAL"         
echo -e "$YELLOW |000        000000   000       000     000  0000      0000000000000         0000    |$NORMAL"
echo -e "$YELLOW |000          0000      0000000        0000000        0000000000000    0000000      |$NORMAL"
line
